name: NoRegionCamping
description: Cancel WorldGuard region entry and selected commands while player is in PvP fight. Lets choose if to kill PvP loggers.
version: 0.1.1.1
author: UltraMC
website: http://serweryminecraft24.pl

main: pl.serweryminecraft24.noregioncamping.PluginNoRegionCamping
depend: [WorldGuard]

commands:
   amifighting:
      description: Tells are you at PvP fihgt and is it safe to log off
      usage: /<command>
   af:
      description: Shorthand for command /amifighting
      usage: /<command>
